# Generated by Django 4.2.1 on 2023-05-19 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип климата',
                'verbose_name_plural': 'Типы климата',
            },
        ),
        migrations.CreateModel(
            name='DaylightHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Световой день',
                'verbose_name_plural': 'Световые дни',
            },
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Препарат',
                'verbose_name_plural': 'Препараты',
            },
        ),
        migrations.CreateModel(
            name='PlantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('sowing_period', models.CharField(max_length=100, verbose_name='Период посева')),
                ('harvest_period', models.CharField(max_length=100, verbose_name='Период сбора')),
                ('chemical_composition', models.TextField(verbose_name='Химический состав')),
                ('medical_preparations', models.TextField(verbose_name='Лекарственные препараты')),
                ('raw_material_need', models.PositiveIntegerField(verbose_name='Количество необходимого сырья (тонны)')),
                ('in_red_book', models.BooleanField(verbose_name='В красной книге')),
                ('region_red_book', models.CharField(blank=True, max_length=100, null=True, verbose_name='Регион в красной книге')),
            ],
            options={
                'verbose_name': 'Информация о растении',
                'verbose_name_plural': 'Информация о растениях',
            },
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Тип почвы',
                'verbose_name_plural': 'Типы почвы',
            },
        ),
        migrations.CreateModel(
            name='PlantRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.climate')),
                ('daylight_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.daylighthours')),
                ('pills', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.pills')),
                ('soil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.soil')),
            ],
            options={
                'verbose_name': 'Запрос на растение',
                'verbose_name_plural': 'Запросы на растения',
            },
        ),
    ]
