# Generated by Django 4.2.1 on 2023-05-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daylighthours',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Время суток'),
        ),
        migrations.AlterField(
            model_name='pills',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='plantrequest',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='plantrequest',
            name='daylight_hours',
        ),
        migrations.RemoveField(
            model_name='plantrequest',
            name='pills',
        ),
        migrations.RemoveField(
            model_name='plantrequest',
            name='soil',
        ),
        migrations.AddField(
            model_name='plantrequest',
            name='climate',
            field=models.ManyToManyField(blank=True, null=True, to='plants.climate', verbose_name='Тип климата'),
        ),
        migrations.AddField(
            model_name='plantrequest',
            name='daylight_hours',
            field=models.ManyToManyField(blank=True, null=True, to='plants.daylighthours', verbose_name='Световой день'),
        ),
        migrations.AddField(
            model_name='plantrequest',
            name='pills',
            field=models.ManyToManyField(blank=True, null=True, to='plants.pills', verbose_name='Препараты'),
        ),
        migrations.AddField(
            model_name='plantrequest',
            name='soil',
            field=models.ManyToManyField(blank=True, null=True, to='plants.soil', verbose_name='Тип почвы'),
        ),
    ]
