# Generated by Django 4.2.1 on 2023-05-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_daylighthours_name_alter_pills_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantrequest',
            name='climate',
            field=models.ManyToManyField(blank=True, to='plants.climate', verbose_name='Тип климата'),
        ),
        migrations.AlterField(
            model_name='plantrequest',
            name='daylight_hours',
            field=models.ManyToManyField(blank=True, to='plants.daylighthours', verbose_name='Световой день'),
        ),
        migrations.AlterField(
            model_name='plantrequest',
            name='pills',
            field=models.ManyToManyField(blank=True, to='plants.pills', verbose_name='Препараты'),
        ),
        migrations.AlterField(
            model_name='plantrequest',
            name='soil',
            field=models.ManyToManyField(blank=True, to='plants.soil', verbose_name='Тип почвы'),
        ),
    ]
