# Generated by Django 4.2.1 on 2023-05-20 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plantinfo_climate_plantinfo_daylight_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantinfo',
            name='chemical_composition',
            field=models.TextField(blank=True, null=True, verbose_name='Химический состав'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='climate',
            field=models.ManyToManyField(blank=True, null=True, to='plants.climate', verbose_name='Типы климата'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='daylight_hours',
            field=models.ManyToManyField(blank=True, null=True, to='plants.daylighthours', verbose_name='Световой день'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='harvest_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период сбора'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='in_red_book',
            field=models.BooleanField(blank=True, null=True, verbose_name='В красной книге'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='medical_preparations',
            field=models.TextField(blank=True, null=True, verbose_name='Лекарственные препараты'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='pills',
            field=models.ManyToManyField(blank=True, null=True, to='plants.pills', verbose_name='Препараты'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='raw_material_need',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество необходимого сырья (тонны)'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='soil',
            field=models.ManyToManyField(blank=True, null=True, to='plants.soil', verbose_name='Типы почвы'),
        ),
        migrations.AlterField(
            model_name='plantinfo',
            name='sowing_period',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Период посева'),
        ),
    ]
